project_id = "xepfrqhuoeijhphkcovz"

[functions.submit-game]
verify_jwt = false

[functions.submit-dictation-game]
verify_jwt = false

[functions.generate-passage]
verify_jwt = false

[functions.upload-avatar]
verify_jwt = false

[functions.evaluate-sentence]
verify_jwt = false

[functions.generate-vocabulary]
verify_jwt = false

[functions.send-child-link-notification]
verify_jwt = false

[functions.generate-intuition-questions]
verify_jwt = false

[functions.submit-intuition-game]
verify_jwt = false
